// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHWAL53etrecxRrFKJKMC0xYgt9a5-tPw',
    appId: '1:732546232451:web:7d354a9d73d9e28960abb6',
    messagingSenderId: '732546232451',
    projectId: 'chat-app-9903c',
    authDomain: 'chat-app-9903c.firebaseapp.com',
    storageBucket: 'chat-app-9903c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGP7ga921RL8X73G9ezys_YU36g6SaVHI',
    appId: '1:732546232451:android:695cabf08230380a60abb6',
    messagingSenderId: '732546232451',
    projectId: 'chat-app-9903c',
    storageBucket: 'chat-app-9903c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUgqtfozQ0HRH1hs0ckaNMcVicwHZMWYU',
    appId: '1:732546232451:ios:b2107553b41286e760abb6',
    messagingSenderId: '732546232451',
    projectId: 'chat-app-9903c',
    storageBucket: 'chat-app-9903c.appspot.com',
    iosClientId: '732546232451-drjrpqnolkpj5p3jgealdqt6stbt4phi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUgqtfozQ0HRH1hs0ckaNMcVicwHZMWYU',
    appId: '1:732546232451:ios:f7336c9609827cd160abb6',
    messagingSenderId: '732546232451',
    projectId: 'chat-app-9903c',
    storageBucket: 'chat-app-9903c.appspot.com',
    iosClientId: '732546232451-vssqpgts93easmcivk1lkob4gl8ibgth.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
